# Generated by Django 5.2.1 on 2025-06-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo_userfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
